name: Unit tests

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:

  tests:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - php: '8.1'
            mode: low-deps
          - php: '8.1'
          - php: '8.2'
            mode: low-deps
          - php: '8.2'
          - php: '8.3'
            mode: low-deps
          - php: '8.3'
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          ini-values: date.timezone=Europe/Paris,memory_limit=-1,default_socket_timeout=10,session.gc_probability=0,apc.enable_cli=1
          php-version: "${{ matrix.php }}"
          extensions: "${{ env.extensions }}"
          tools: flex

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-progress $([ '${{ matrix.mode }}' = low-deps ] && echo '--prefer-lowest')

      - name: Run phpspec tests
        run: |
          php vendor/bin/phpspec run
